# Generated by Django 6.0.3 on 2026-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
